lista_compras/api/urls.py
from django.urls import path, include
from rest_framework import routers
from .views import ItemViewSet


router = routers.DefaultRouter()
router.register("items", ItemViewSet)

app_name = "api"

urlpatterns = [
    path("", include(router.urls))
]

lista_compras/lista/urls.py
from django.urls import path
from .views import list_items, desativar_items, detail_items, edit_items, add_items

app_name = "lista"

urlpatterns = [
    path("", list_items, name="items"),
    path("adicionar/", add_items, name="adicionar"),
    path("<int:item_pk>/", detail_items, name="detalhes"),
    path("<int:item_pk>/editar/", edit_items, name="editar"),
    path("<int:item_pk>/desativar/", desativar_items, name="desativar"),
]

lista_compras/urls.py
from django.contrib import admin
from django.urls import path, include
from .lista import urls as items_urls
from .api import urls as api_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include((items_urls, "lista"), namespace="items")),
    path('api/', include(api_urls, namespace="api")),
]

lista_compras/lista/models.py
from django.db import models


class Item(models.Model):
    ITEM_STATUS = [
        ("ativo", "Ativo"),
        ("desativado", "Desativado")
    ]
    nome = models.CharField("Nome", max_length=100)
    quantidade = models.IntegerField("Quantidade")
    status = models.CharField("Status", default="ativo", choices=ITEM_STATUS, max_length=10)

lista_compras/lista/forms.py
from django import forms

from .models import Item


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ("nome", "status", "quantidade")

lista_compras/api/views.py
from rest_framework import viewsets
from lista_compras.lista.models import Item
from .serializers import ItemSerializer


class ItemViewSet(viewsets.ModelViewSet):
    queryset = Item.objects.all()
    serializer_class = ItemSerializer

lista_compras/lista/views.py
from django.shortcuts import render, reverse, get_object_or_404, redirect

from .models import Item
from .forms import ItemForm


def list_items(request):
    lista_items = Item.objects.all()

    return render(request, "item/list.html", context={"lista_items": lista_items})


def add_items(request):
    form = ItemForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect(reverse("items:items"))

    return render(request, "item/add.html", context={"form": form})


def detail_items(request, item_pk):
    item = get_object_or_404(Item.objects, pk=item_pk)

    return render(request, "item/detail.html", context={"item": item})


def edit_items(request, item_pk):
    item = get_object_or_404(Item.objects, pk=item_pk)
    form = ItemForm(request.POST or None, instance=item)

    if form.is_valid():
        form.save()
        return redirect(reverse("items:items"))

    return render(request, "item/edit.html", context={"item": item, "form": form})


def desativar_items(request, item_pk):
    item = get_object_or_404(Item.objects, pk=item_pk)

    item.delete()
    #item.status = "desativado"
    #item.save()

    return redirect(reverse("items:items"))

lista_compras/lista/templates/item/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Meus Items</title>
</head>
<body>

<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <a class="navbar-brand" href="{% url 'items:items' %}">Adicionar Items</a>
</nav>

<main role="main" class="container">

    <div class="row">
        <form method=POST>
            {% csrf_token %}
            {{ form }}
            <button type="submit">Adicionar</button>
        </form>
    </div>

</main>

</body>
</html>

lista_compras/lista/templates/item/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Meus Items</title>
</head>
<body>

<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <a class="navbar-brand" href="{% url 'items:items' %}">Meus Items</a>
</nav>

<main role="main" class="container">

    <div class="row">
        <h5>{{item.nome}}</h5>
        <p>{{item.quantidade}}</p>
        <p>{{item.status}}</p>
    </div>

</main>

</body>
</html>

lista_compras/lista/templates/item/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Meus Items</title>
</head>
<body>

<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <a class="navbar-brand" href="{% url 'items:items' %}">Editar Items</a>
</nav>

<main role="main" class="container">

    <div class="row">
        <form method=POST>
            {% csrf_token %}
            {{ form }}
            <button type="submit">Editar</button>
        </form>
    </div>

</main>

</body>
</html>

lista_compras/lista/templates/item/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Meus Items</title>
</head>
<body>

<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <a class="navbar-brand" href="{% url 'items:items' %}">Meus Items</a>
    <a class="navbar-brand" href="{% url 'items:adicionar' %}">Adicionar Item</a>
</nav>

<main role="main" class="container">

    <div class="row">
        {% for item in lista_items %}
            <div class="col-3">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">{{ item.nome }}</h5>
                        <p class="card-text">{{ item.status }}</p>
                        <a href="{% url 'items:detalhes' item.id %}" class="btn btn-success">Ver item</a>
                        <a href="{% url 'items:desativar' item.id %}" class="btn btn-warning">desativar item</a>
                        <a href="{% url 'items:editar' item.id %}" class="btn btn-primary">editar item</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

</main>

</body>
</html>